### ISSUE TITLE
Syntax Error while loading YAML.

### ISSUE THREAD

**Issue by patsevanton** [one-mINd/harbor_ansible_role#9]
Hello!
Thanks for role
I try install and get error

```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/user/github/infrastructure-as-a-code-example/12-harbor/playbook.yml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - one_mind.harbor_ansible_role
    vars:
    ^ here
```

Playbook
```
- hosts: servers
  roles:
      - one_mind.harbor_ansible_role
    vars:
    
      # create
      harbor_projects:
        - project_name: "firstproject"
          public: "true"
        - project_name: "secondproject"
          public: "false"
      harbor_members: 
        - project: "firstproject"
          role_id: 1
          username: "user_one"
        - project: "secondproject"
          role_id: 2
          username: "second_one"
      harbor_users:
        - username: "user_one"
          email: "email@mail.com"
          password: "harboruser12345"
          realname: "user one"
          comment: "void"
        - username: "second_one"
          email: "email_two@mail.com"
          password: "harboruser12345"
          realname: "user two"
          comment: "void"
          
        # get
        harbor_get_users: yes
        harbor_get_projects: yes
        harbor_get_members:
          - project_id: firstproject
          - project_id: secondproject
        
        # remove
        harbor_remove_users:
          - user_id: 1
          - user_id: 2
        harbor_remove_members:
          - project_id: 1
            member_id: 1
          - project_id: 2
            member_id: 2
        harbor_remove_projects:
          - project_id: 1
          - project_id: 2
```
